# Generated by Django 4.1.7 on 2023-04-04 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
